# Top level configuration

# Last Release 1.0.2   2025-02-01_202626
SuiteVersion: 1.0.3

SuiteName: RM_Utilities_Suite

ProjectRootDirPath: C:\Users\rotter\dev\Genealogy\repo Genealogy-scripts

ProjectList:
 - Change source for citation
 - Change source template
 - Color from group
 - Convert fact
 - Group from SQL
 - List citations for PersonID
 - Lump sources
 - Modify citation list
 - Run SQL
 - Test external files
 - External Files Info



