# Top level configuration

# Last Release 1.0.2   2025-02-01_202626
SuiteVersion: 1.0.3

SuiteName: RM_Utilities_Suite

ProjectRootDirPath: C:\Users\rotter\Development\Genealogy\repo Genealogy-scripts\RM

ProjectList:
 - Change source for citation
 - Change source template
 - Modify citation list
 - Color from group
 - Convert Fact
 - Group from SQL
 - List citations for PersonID
 - Run SQL
 - Test external files
 - Lump sources

 

